services:
  svelte:
    build: ./skeleton_svelte
    ports:
      - "4001:4001"
  backend:
    build: ./backend
    environment:
      URL_LENGTH: "1024"
      POSTGRES_DATABASE_URL: "postgresql://postgres:hello@postgres:5432"
      DATABASE_TIMEOUT: "30"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: hello
    ports:
      - "8080:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 3
